# Site settings
title: Introduction to Machine Learning
email: anna.scaife@manchester.ac.uk
description: "CERN School of Computing 2019: lectures and tutorials on machine learning"
baseurl: ""
url: "http://as595.github.io"
twitter_username: radastrat
github_username:  as595

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
